config/routes.rb
Rails.application.routes.draw do

  
  # 自分で指定したcontrollerを見に行く
  # defautlの場合はgemの中にあるcontrollerを見に行く(表側に出ていない)
  # 自由にいじれない
  devise_for :users, :controllers => {
    :registrations => "users/registrations",
    :sessions => "users/sessions"
  }

  resources :departments, except: [:show]

  resources :employees, except: [:index, :show]
  root 'employees#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/department.rb
# == Schema Information
#
# Table name: departments
#
#  id         :bigint(8)        not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  company_id :bigint(8)
#

class Department < ApplicationRecord
  has_many :employees
  belongs_to :company
  validates :name, presence: true, uniqueness: {scope: [:company_id]}
  validates :company_id, presence: true 
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
 before_action :authenticate_user!
 before_action :correct_user, only: [:edit, :update, :destroy]
  def index
    company = current_user.company
    @departments = company.departments
  end

  def new
    @department = Department.new
  end

  def create
    company = current_user.company
    @department = company.departments.build(department_params)
    if @department.save
      redirect_to departments_path and return
    else
      # renderは何かを描画するときに使う
      # ここではアクションではなく、"new"のViewを呼んでいる
      render "new"
    end
  end

  def edit
    @department = Department.find(params[:id])
  end

  def update
    @department = Department.find(params[:id])
    if @department.update_attributes(department_params)
      redirect_to departments_url and return
    else
      render "edit"
    end
  end

  def destroy
    Department.find(params[:id]).destroy
    redirect_to departments_url and return
  end

  private
    
    def department_params
      params.require(:department).permit(:name)
    end

    def correct_user
      department = Department.find(params[:id])
      redirect_to departments_path and return unless department.company == current_user.company
    end
      
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/edit.html.slim
h1 部署データを変更します
= form_for @department do |f|
  = render "shared/error_messages", object: f.object
  = f.label "名前："
  = f.text_field :name

  = f.submit "変更"

app/views/departments/index.html.slim
h1 部署一覧：
table
  tr
    th ID
    th 部署名
  - @departments.each do |department|
    tr
      td #{department.id}
      td #{department.name}
      td 
        = link_to edit_department_path(department) do 
          button 編集
      td
        = link_to department_path(department), method: :delete, data: {confirm: "削除します"} do
          button 削除

= link_to new_department_path do 
  button 新規追加

app/views/departments/new.html.slim
h1 部署データを新規作成します
= form_for(@department) do |f|
  = render "shared/error_messages", object: f.object
  = f.label "名前："
  = f.text_field :name 

  = f.submit "設定"